[package]
name = "pg"
version = "0.1.0"
authors = ["Jorge Aparicio <japaricious@gmail.com>"]

[dependencies.f3]
default-features = false
features = [
    "default-exception-handler",
    "default-panic-fmt",
]
version = "0.2.0"
